steps:
  # -----------------------------------------------------------------------------
  # 1. Construir la Flex Template (Imagen Docker + JSON Spec en GCS)
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: Build Dataflow Flex Template
    args: ['dataflow', 'flex-template', 'build',
           'gs://$_DATAFLOW_BUCKET/templates/$_TEMPLATE_NAME.json',
           '--image-gcr-path=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA',
           '--flex-template-base-image=PYTHON3',
           '--sdk-language=PYTHON',
           '--py-path=.',
           '--env=FLEX_TEMPLATE_PYTHON_PY_FILE=$_PYTHON_FILE',
           '--env=FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=$_REQUIREMENTS_FILE'
    ]
    waitFor: ['-']

  # -----------------------------------------------------------------------------
  # 2. Ejecutar (o Actualizar) el Job de Dataflow
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: Run Dataflow Job
    args: ['dataflow', 'flex-template', 'run', '$_JOB_NAME',
           '--template-file-gcs-location=gs://$_DATAFLOW_BUCKET/templates/$_TEMPLATE_NAME.json',
           '--region=$_REGION',
           '--num-workers=$_MIN_WORKERS',
           '--max-workers=$_MAX_WORKERS',
           '--service-account-email=$_SERVICE_ACCOUNT',
           '--parameters=project_id=$PROJECT_ID,victimas_pubsub_subscription_name=$_SUB_VICTIMAS,agresores_pubsub_subscription_name=$_SUB_AGRESORES,firestore_db=$_FIRESTORE_DB,firestore_collection=$_FIRESTORE_COLLECTION,alertas_policia_topic=$_TOPIC_POLICIA,db_host=$_DB_HOST,db_user=$_DB_USER,db_pass=$_DB_PASS,db_name=$_DB_NAME'
    ]
    waitFor: ['Build Dataflow Flex Template']

options:
  logging: STACKDRIVER_ONLY

substitutions:
  _REGION: europe-west6
  _DATAFLOW_BUCKET: bucket-dataflow
  _REPO_NAME: repo-imagenes-proyecto      # Tu repo en Artifact Registry
  _IMAGE_NAME: dataflow-img
  _JOB_NAME: pipeline-alertas-seguridad
  _TEMPLATE_NAME: template-alertas
  _PYTHON_FILE: dataflow_firestore.py
  _REQUIREMENTS_FILE: requirements.txt
  _SERVICE_ACCOUNT: tu-sa-dataflow@$PROJECT_ID.iam.gserviceaccount.com
  _SUB_VICTIMAS: victimas-datos-sub
  _SUB_AGRESORES: agresores-datos-sub
  _TOPIC_POLICIA: policia-alertas
  _FIRESTORE_DB: (default)
  _FIRESTORE_COLLECTION: alertas_activas
  _DB_HOST: 10.123.0.5       # IP de tu Cloud SQL o Instancia
  _DB_NAME: seguridad_db
  _DB_USER: admin_app
  _DB_PASS: tu_password_segura