steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'Terraform'
    args: [
      'build', 
      '-t', 'europe-west6-docker.pkg.dev/data-project-streaming-487217/repo-imagenes-proyecto/crear_tablas:$COMMIT_SHA', 
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'europe-west6-docker.pkg.dev/data-project-streaming-487217/repo-imagenes-proyecto/crear_tablas:$COMMIT_SHA'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'jobs', 'update', 'crear-tablas',
      '--image', 'europe-west6-docker.pkg.dev/data-project-streaming-487217/repo-imagenes-proyecto/crear_tablas:$COMMIT_SHA',
      '--region', 'europe-west6'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'jobs', 'execute', 'crear-tablas',
      '--region', 'europe-west6',
      '--wait'
    ]

options:
  logging: CLOUD_LOGGING_ONLY