steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'dbt/dbt_dp2'
    args: [
      'build', 
      '-t', 'europe-west6-docker.pkg.dev/$PROJECT_ID/repo-imagenes-proyecto/dbt-alertas:$COMMIT_SHA', 
      '-t', 'europe-west6-docker.pkg.dev/$PROJECT_ID/repo-imagenes-proyecto/dbt-alertas:latest', 
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west6-docker.pkg.dev/$PROJECT_ID/repo-imagenes-proyecto/dbt-alertas:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'jobs', 'update', 'dbt-alertas-job',
        '--image', 'europe-west6-docker.pkg.dev/$PROJECT_ID/repo-imagenes-proyecto/dbt-alertas:$COMMIT_SHA',
        '--region', 'europe-west6'
      ]

images:
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/repo-imagenes-proyecto/dbt-alertas:latest'
options:
  logging: CLOUD_LOGGING_ONLY