dbt_dp2:
  outputs:
    dev:
      dataset: analitical_dataset5
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west6
      method: oauth
      priority: interactive
      project: data-project-streaming-487217
      threads: 1
      type: bigquery
  target: dev